version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 80:8080
    volumes:
      - ./src:/var/www/html
